language: c
sudo: false
dist: xenial
env:
  global:
    - PATH=~/.roswell/bin:~/.linuxbrew/bin:$PATH
    - ROSWELL_BRANCH=$TRAVIS_BRANCH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_QUICKLISP_DIST_URI=https://github.com/roswell/quicklisp/releases/download/dist/quicklisp.txt
    - ROSWELL_REPO=https://github.com/${TRAVIS_REPO_SLUG}
  matrix:
    - METHOD=ci LISP=alisp
    - METHOD=ci LISP=cmu-bin/2017-10
    - METHOD=ci LISP=sbcl
    - METHOD=ci LISP=ecl
    - METHOD=ci LISP=mkcl
    - METHOD=ci LISP=clisp
    - METHOD=ci LISP=abcl
    - METHOD=ci LISP=ccl-bin
    - METHOD=brew
    - METHOD=ci LISP=sbcl/1.1.14
    - METHOD=ci LISP=ccl32
    - METHOD=ci LISP=sbcl/git

os:
  - osx
  - linux

cache:
  directories:
    - $HOME/.rosproxy

matrix:
  allow_failures:
    - env: METHOD=brew
    - env: METHOD=ci LISP=sbcl/git
    - env: METHOD=ci LISP=mkcl
  include:
      - sudo: required
        os: linux
        env: METHOD=valgrind XCFLAGS="-g -O0"
      - sudo: required
        os: linux
        env: METHOD=documents

#branches:
#  except:
#      - /^v[0-9]/

addons:
  apt:
    packages:
      - libc6-i386
#      - gcc-multilib
#      - gcc-mingw-w64-i686
#      - binutils-mingw-w64-i686
#      - wine

before_install:
  - date
  - if [ $METHOD = documents ]; then find . \( -name \*.c -o -name \*.h \) -type f|xargs wc -l -c; fi
  - if [ $METHOD = documents ]; then find . \( -name \*.lisp -o -name \*.ros \) -type f|xargs wc -l -c; fi
  - if [ $METHOD = documents ] || [ $METHOD = valgrind ]; then
       sudo apt-get -qq update --force-yes > /dev/null; fi
  - if [ $METHOD = brew ] && [ $TRAVIS_OS_NAME = linux ]; then
       yes ""| sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"; fi
  - if [ $METHOD = brew ] || [ $TRAVIS_OS_NAME = osx ]; then brew update;brew --env;brew config; fi
  - if [ $METHOD = brew ]; then brew update;brew doctor || true; fi

install:
  - if ! [ -f "$HOME/.rosproxy/proxy" ]; then
      curl -L https://github.com/snmsts/roswell-proxy/releases/download/v0.5/v0.5-$TRAVIS_OS_NAME.tgz |tar xzf -;
      cp proxy $HOME/.rosproxy/proxy;
    fi
  - $HOME/.rosproxy/proxy daemon
  - mkdir ~/.roswell
  - echo "ros.proxy	0	localhost:5000" > ~/.roswell/config
  - echo "proxy.http.only	0	1" >> ~/.roswell/config
  - if [ $METHOD = documents ]; then sudo apt-get install -qq pandoc ruby-sass; pandoc -v; fi
  - if [ $METHOD = valgrind ];  then sudo apt-get install -qq valgrind > /dev/null; fi
  - if [ $METHOD = brew ] && [ $TRAVIS_OS_NAME = linux ]; then brew install curl ; fi
  - if [ x$XCC = xi686-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-i686 binutils-mingw-w64-i686; fi
  - if [ x$WINE != x ]; then sudo apt-get install -qq wine > /dev/null; fi
  - if [ x$APT_UNINSTALL != x ]; then sudo apt-get purge -qq $APT_UNINSTALL; fi

script:
  - if [ "$METHOD" = "documents" ]; then
      rm documents/man/* documents/html/*;
      sh bootstrap;
      ./configure --enable-manual-generation --enable-html-generation;
      make;
      sudo make install;
    fi
  - if [ "$METHOD" = "brew" ]; then brew install roswell --HEAD; fi
  - if [ "$METHOD" = "ci" ]; then sh ./scripts/install-for-ci.sh; fi
  - if [ "$METHOD" = "valgrind" ]; then
       sh bootstrap;
       CFLAGS=$XCFLAGS ./configure --disable-dependency-tracking --disable-maintainer-mode;
       make;
       sudo make install;
       make maintainer-clean;
    fi
  - if [ "$METHOD" = "brew" ] || [ "$METHOD" = "ci" ]; then
       ros version;
       ros version=t run;
       ros install prove;
       run-prove roswell-test.asd 2>&1;
    fi
  - if [ "$METHOD" = "ci" ]; then
       ros -q run && [`ros -q run 2>&1` == ""];
    fi
  - if [ "$LISP" = "sbcl-bin" ] && [ x$ALLOW_FAILURES != x ]; then
       if [ $TRAVIS_OS_NAME = osx ]; then
          sudo ros -e '(ignore-errors (with-open-file (o (format nil "/~A" (code-char 12354)) :direction :output)))';
       fi;
       if [ $ALLOW_FAILURES = YES ]; then
         ros sbcl.patchless=t install sbcl;
       else
         ros install sbcl --sbcl-bin;
         [`ros -e "(ros:ignore-shebang)" -e '(loop for x in (directory "src/lisp/*.ros") do (load x))' 2>&1` == ""];
       fi;
       make -C t/tree-shaker ;
    fi
  - ros config
  - cat /tmp/proxy-log || true
  - pkill -9 proxy

after_success:
  - $HOME/.rosproxy/proxy daemon
  - if [ "$METHOD" = "documents" ] || [ $METHOD = brew ]; then
       git config user.email "auto@example.com";
       git config user.name "Travis-CI";
    fi
  - if [ "$METHOD" = "valgrind" ]; then
       ros setup;
       valgrind --leak-check=yes ros config;
    fi
  - if [ "$METHOD" = "documents" ]; then
       git branch;git status;
       git checkout $TRAVIS_BRANCH;git add -u;git add documents/man/* documents/html/*;
       git commit -m "[ci skip] documents update";
    fi
  - if [ "$METHOD" = "documents" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
       git push --force --quiet "https://${GITHUB_OAUTH_TOKEN}:x-oauth-basic@github.com/roswell/roswell.git" $TRAVIS_BRANCH > /dev/null 2>&1; fi
  - pkill -9 proxy
