language: c
sudo: false
dist: xenial
env:
  global:
    - PATH=~/.roswell/bin:~/.linuxbrew/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_QUICKLISP_DIST_URI=https://github.com/roswell/quicklisp/releases/download/dist/quicklisp.txt

  matrix:
    - METHOD=ci LISP=sbcl-bin
    - METHOD=ci LISP=ccl-bin
    - METHOD=ci LISP=alisp
    - METHOD=ci LISP=cmu-bin/2017-10
    - METHOD=ci LISP=sbcl
    - METHOD=ci LISP=ecl
    - METHOD=ci LISP=mkcl
    - METHOD=ci LISP=clisp
    - METHOD=ci LISP=abcl
    - METHOD=ci LISP=ccl32

os:
  - windows
  - linux
  - osx

cache:
  directories:
    - $HOME/.rosproxy

matrix:
  allow_failures:
    - env: METHOD=ci LISP=mkcl
      os: osx
    - env: METHOD=ci LISP=mkcl
      os: windows

#branches:
#  except:
#      - /^v[0-9]/

addons:
  apt:
    packages:
      - libc6-i386
#      - gcc-multilib
#      - gcc-mingw-w64-i686
#      - binutils-mingw-w64-i686
#      - wine

before_install:
  - date

script:
  - if [ "$METHOD" = "ci" ]; then curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | bash -xv ; fi
  - if [ "$METHOD" = "ci" ]; then
       ros version;
       ros version=t run;
       ros install prove;
       run-prove roswell-test.asd 2>&1;
    fi
  - if [ "$METHOD" = "ci" ]; then
       ros -q run && [`ros -q run 2>&1` == ""];
    fi
  - ros config
